### ISSUE TITLE
Passwords are stored in clear text in session-store.json

### ISSUE THREAD

**Issue by ghdt1** [subhra74/snowflake#52]
Passwords are stored in clear text in the session-store.json file!  This is a huge security risk.  The passwords need to be stored encrypted to ensure security.

**Comment by subhra74** [comment]
There is plan to use master password to encrypt passwords on next release. Currently if you do not wish to store them in unencrypted form, keep the password field blank in connection manager. Also it’s always recommend to use key based authentication.

**Comment by waterwingz** [comment]
If you don't save passwords, the popup password box used (at least in the Windows version) is a bit annoying. The mouse cursor focus does not move to the text entry field and pressing Enter to complete password entry does nothing. This requires moving hand to mouse a couple of times for what should be just a keyboard exercise.  (Great program otherwise!)

**Comment by ghdt1** [comment]
@subhra74 Thank you for your great work on the app!  We do use key based auth but on occasion need to use password and so will keep those password fields blank for now.  Look forward to the next release.

**Comment by subhra74** [comment]
@ghdt1 Thanks for pointing about the plain text password though, I feel that user should know, how the password is being stored. For now warning text have been added that passwords will be stored in plain text. For now it's upto the user to decide between convenience and security. Also the focus problem has been resolved. Pressing enter will accept the entered password. 
Master password functionality will solve the issue properly
